version: 2
run: &run
  docker:
    - image:  circleci/python:3.7
  steps:
    - checkout
    - run:
        command: |
          apk update && apk upgrade && apk add git
          pip install --upgrade pip
          pip install -r requirements.txt
          python ./get_repos.py $ENVIRONMENT
jobs:
  test:
    docker:
      - image:circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            mv mock_repositories/* .
            apk update && apk upgrade && apk add git && apk add build-base
            pip install --upgrade pip
            pip install -r requirements_pytest.txt
            pycodestyle ./get_repos.py
            pylint --disable=R0902,R0913,R0123,W0703 ./get_repos.py
            pycodestyle ./test_get_repos.py --max-line-length=150
            pylint --disable=C0301 ./test_get_repos.py
            pytest -v
  run-staging:
    <<: *run
    environment:
      ENVIRONMENT: "staging"
  run-prod:
    <<: *run
    environment:
      ENVIRONMENT: "prod"
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run-prod
      - run-staging
  release-pipeline:
    jobs:
      - test
      - run-staging:
          requires:
            - test
          filters:
            branches:
              only:
                 - master
                 - staging
                 - CICD-148
      - prod-approval:
          type: approval
          requires:
            - run-staging
          filters:
            branches:
              only: master
      - run-prod:
          requires:
            - prod-approval
          filters:
            branches:
              only: master
